version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Asia/Tehran
    open-pull-requests-limit: 10
    groups:
      python-runtime:
        dependency-type: production
      python-development:
        dependency-type: development

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Asia/Tehran
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Tehran
    open-pull-requests-limit: 5
